"""Formats the output of pow_pp.sollya into src/pow_pp_table.rs; see there."""

import sys

coefs = []
table = []
pp_bits = None
relerr = None
for line in sys.stdin:
    parts = line.split()
    if not parts:
        continue
    if parts[0] == "COEF":
        coefs.append(parts[1])
    elif parts[0] == "TBL":
        table.append(parts[1])
    elif parts[0] == "PP":
        pp_bits = parts[1]
    elif parts[0] == "RELERR":
        relerr = "".join(parts[1:])

assert pp_bits == "0x3fd4a6240b3bbe1a", pp_bits
assert len(coefs) == 17, len(coefs)
assert len(table) == 2047, len(table)

print(f"""\
//! Generated by `sollya pow_pp.sollya | python3 pow_pp_to_rs.py`, both in
//! the scripts/ directory. Do not edit by hand.
//!
//! Data for `pow_pp`, the x^PP kernel specialized for the DTW cost exponent
//! PP = 0.32264042946823823 (bits {pp_bits}).

/// Coefficients of t^1 .. t^17 of the minimax polynomial for (1+t)^PP,
/// t in [sqrt(0.5)-1, sqrt(2)-1]. The t^0 coefficient is exactly 1.
/// Relative error {relerr}.
#[rustfmt::skip]
pub(crate) const POLY: [f64; 17] = [""")
for c in coefs:
    print(f"    f64::from_bits({c}),")
print("""];

/// Bits of 2^(PP*k), correctly rounded, for k in -1022..=1024, indexed by
/// k + 1022. This covers every k the range reduction can produce for a
/// positive normal input.
#[rustfmt::skip]
pub(crate) static EXP_TABLE: [u64; 2047] = [""")
for i in range(0, len(table), 4):
    print("    " + " ".join(f"{v}," for v in table[i : i + 4]))
print("];")
