"""Formats the output of pow_nsim.sollya into src/pow_nsim_table.rs; see there."""

import sys

DEGREES = {"P0": 6, "P1": 8}


coefs: dict[str, list[str]] = {"P0": [], "P1": []}
tables: dict[str, list[str]] = {"P0": [], "P1": []}
relerr: dict[str, str] = {}
exponents: dict[str, str] = {}
for line in sys.stdin:
    parts = line.split()
    if not parts:
        continue
    if parts[0] == "COEF":
        coefs[parts[1]].append(parts[2])
    elif parts[0] == "TBL":
        tables[parts[1]].append(parts[2])
    elif parts[0] == "RELERR":
        relerr[parts[1]] = "".join(parts[2:])
    elif parts[0] == "EXP":
        exponents[parts[1]] = parts[2]

for name, deg in DEGREES.items():
    assert len(coefs[name]) == deg, (name, len(coefs[name]))
    assert len(tables[name]) == 255, (name, len(tables[name]))
    assert name in relerr and name in exponents

print(f"""\
//! Generated by `sollya pow_nsim.sollya | python3 pow_nsim_to_rs.py`, both in
//! the scripts/ directory. Do not edit by hand.
//!
//! Data for `pow_p0`/`pow_p1`, the x^P kernels specialized for the NSIM
//! aggregation exponents P0 = {float(exponents["P0"])} and
//! P1 = {float(exponents["P1"])}.""")
for name, deg in DEGREES.items():
    print(f"""
/// Coefficients of t^1 .. t^{deg} of the minimax polynomial for (1+t)^{name},
/// t in [sqrt(0.5)-1, sqrt(2)-1]. The t^0 coefficient is exactly 1.
/// Relative error {relerr[name]}.
#[rustfmt::skip]
pub(crate) const {name}_POLY: [f32; {deg}] = [""")
    for c in coefs[name]:
        print(f"    f32::from_bits({c}),")
    print(f"""];

/// Bits of 2^({name}*k), correctly rounded to f32, for k in -126..=128,
/// indexed by k + 126. This covers every k the range reduction can produce
/// for a positive normal f32 input (2^({name}*128) overflows to inf, matching
/// powf).
#[rustfmt::skip]
pub(crate) static {name}_EXP_TABLE: [u32; 255] = [""")
    for i in range(0, len(tables[name]), 8):
        print("    " + " ".join(f"{v}," for v in tables[name][i : i + 8]))
    print("];")
