"""Formats pow_two_f.sollya output as two-f-model/src/pow_table.rs."""

import sys

expected = {
    "P005": (1, 20, 17),
    "P04": (2, 5, 17),
    "P03": (3, 10, 17),
    "P171332": (42833, 25000, 17),
}
decimals = {"P005": "0.05", "P04": "0.4", "P03": "0.3", "P171332": "1.71332"}
coefs = {name: [] for name in expected}
scales = {name: [] for name in expected}
relerr = {}
current = None

for line in sys.stdin:
    parts = line.split()
    if not parts:
        continue
    if parts[0] == "POWER":
        current = parts[1]
        assert tuple(map(int, parts[2:])) == expected[current]
    elif parts[0] == "RELERR":
        relerr[current] = "".join(parts[1:])
    elif parts[0] == "COEF":
        coefs[current].append(parts[1])
    elif parts[0] == "SCALE":
        scales[current].append(parts[1])

for name, (_, _, degree) in expected.items():
    assert len(coefs[name]) == degree, (name, len(coefs[name]))
    expected_scales = 1024 if name == "P171332" else 2047
    assert len(scales[name]) == expected_scales, (name, len(scales[name]))
    assert name in relerr

print("""\
//! Generated by `sollya pow_two_f.sollya | python3 pow_two_f_to_rs.py`, both
//! in the scripts/ directory. Do not edit by hand.
//! Minimax coefficients and exponent scales for the 2f-model's fixed powers.
""", end="")
for name, (numerator, denominator, degree) in expected.items():
    print(f"""
/// Coefficients of t^1 .. t^{degree} for (1+t)^{decimals[name]} (using the
/// binary64 exponent) on [sqrt(0.5)-1, sqrt(2)-1]. Relative error {relerr[name]}.
#[rustfmt::skip]
pub(crate) const {name}_POLY: [f64; {degree}] = [""")
    for value in coefs[name]:
        print(f"    f64::from_bits({value}),")
    print(f"""];
""")
    if name == "P171332":
        print(f"""/// Bits of 2^(({numerator}/{denominator})*k), correctly rounded using the
/// binary64 exponent, for k in -511..=512. Two entries are multiplied to
/// cover a reduced input exponent in -1022..=1024 without premature overflow.
#[rustfmt::skip]
pub(crate) static {name}_HALF_EXP_TABLE: [u64; 1024] = [""")
    else:
        print(f"""/// Bits of 2^(({numerator}/{denominator})*k), correctly rounded using the
/// binary64 exponent, for k in -1022..=1024.
#[rustfmt::skip]
pub(crate) static {name}_EXP_TABLE: [u64; 2047] = [""")
    for index in range(0, len(scales[name]), 8):
        print("    " + " ".join(f"{value}," for value in scales[name][index:index + 8]))
    print("];")
